/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as AssinaturasRouteImport } from './routes/assinaturas'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as LpYealinkVideoconferenciaRouteImport } from './routes/lp.yealink-videoconferencia'
import { Route as LpVideoconferenciaRouteImport } from './routes/lp.videoconferencia'
import { Route as LpServiceDeskRouteImport } from './routes/lp.service-desk'
import { Route as LpRallyBarRouteImport } from './routes/lp.rally-bar'
import { Route as LpPolyStudioRouteImport } from './routes/lp.poly-studio'
import { Route as LpHeadsetsPolyRouteImport } from './routes/lp.headsets-poly'
import { Route as LpHeadsetYealinkRouteImport } from './routes/lp.headset-yealink'
import { Route as LpHeadsetLogitechRouteImport } from './routes/lp.headset-logitech'
import { Route as LpHeadsetCallcenterRouteImport } from './routes/lp.headset-callcenter'
import { Route as LpCabeamentoRouteImport } from './routes/lp.cabeamento'
import { Route as LpAlocacaoTiRouteImport } from './routes/lp.alocacao-ti'
import { Route as SiteSobreRouteImport } from './routes/_site.sobre'
import { Route as SiteProdutosRouteImport } from './routes/_site.produtos'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as SiteServicosIndexRouteImport } from './routes/_site.servicos.index'
import { Route as SiteBlogIndexRouteImport } from './routes/_site.blog.index'
import { Route as SiteServicosDigitalWorkspaceRouteImport } from './routes/_site.servicos.digital-workspace'
import { Route as SiteBlogSlugRouteImport } from './routes/_site.blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturasRoute = AssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const LpYealinkVideoconferenciaRoute =
  LpYealinkVideoconferenciaRouteImport.update({
    id: '/lp/yealink-videoconferencia',
    path: '/lp/yealink-videoconferencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const LpVideoconferenciaRoute = LpVideoconferenciaRouteImport.update({
  id: '/lp/videoconferencia',
  path: '/lp/videoconferencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LpServiceDeskRoute = LpServiceDeskRouteImport.update({
  id: '/lp/service-desk',
  path: '/lp/service-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LpRallyBarRoute = LpRallyBarRouteImport.update({
  id: '/lp/rally-bar',
  path: '/lp/rally-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const LpPolyStudioRoute = LpPolyStudioRouteImport.update({
  id: '/lp/poly-studio',
  path: '/lp/poly-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LpHeadsetsPolyRoute = LpHeadsetsPolyRouteImport.update({
  id: '/lp/headsets-poly',
  path: '/lp/headsets-poly',
  getParentRoute: () => rootRouteImport,
} as any)
const LpHeadsetYealinkRoute = LpHeadsetYealinkRouteImport.update({
  id: '/lp/headset-yealink',
  path: '/lp/headset-yealink',
  getParentRoute: () => rootRouteImport,
} as any)
const LpHeadsetLogitechRoute = LpHeadsetLogitechRouteImport.update({
  id: '/lp/headset-logitech',
  path: '/lp/headset-logitech',
  getParentRoute: () => rootRouteImport,
} as any)
const LpHeadsetCallcenterRoute = LpHeadsetCallcenterRouteImport.update({
  id: '/lp/headset-callcenter',
  path: '/lp/headset-callcenter',
  getParentRoute: () => rootRouteImport,
} as any)
const LpCabeamentoRoute = LpCabeamentoRouteImport.update({
  id: '/lp/cabeamento',
  path: '/lp/cabeamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LpAlocacaoTiRoute = LpAlocacaoTiRouteImport.update({
  id: '/lp/alocacao-ti',
  path: '/lp/alocacao-ti',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSobreRoute = SiteSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProdutosRoute = SiteProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicosIndexRoute = SiteServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicosDigitalWorkspaceRoute =
  SiteServicosDigitalWorkspaceRouteImport.update({
    id: '/servicos/digital-workspace',
    path: '/servicos/digital-workspace',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/assinaturas': typeof AssinaturasRoute
  '/obrigado': typeof ObrigadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contato': typeof SiteContatoRoute
  '/produtos': typeof SiteProdutosRoute
  '/sobre': typeof SiteSobreRoute
  '/lp/alocacao-ti': typeof LpAlocacaoTiRoute
  '/lp/cabeamento': typeof LpCabeamentoRoute
  '/lp/headset-callcenter': typeof LpHeadsetCallcenterRoute
  '/lp/headset-logitech': typeof LpHeadsetLogitechRoute
  '/lp/headset-yealink': typeof LpHeadsetYealinkRoute
  '/lp/headsets-poly': typeof LpHeadsetsPolyRoute
  '/lp/poly-studio': typeof LpPolyStudioRoute
  '/lp/rally-bar': typeof LpRallyBarRoute
  '/lp/service-desk': typeof LpServiceDeskRoute
  '/lp/videoconferencia': typeof LpVideoconferenciaRoute
  '/lp/yealink-videoconferencia': typeof LpYealinkVideoconferenciaRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/servicos/digital-workspace': typeof SiteServicosDigitalWorkspaceRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/servicos/': typeof SiteServicosIndexRoute
}
export interface FileRoutesByTo {
  '/assinaturas': typeof AssinaturasRoute
  '/obrigado': typeof ObrigadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contato': typeof SiteContatoRoute
  '/produtos': typeof SiteProdutosRoute
  '/sobre': typeof SiteSobreRoute
  '/lp/alocacao-ti': typeof LpAlocacaoTiRoute
  '/lp/cabeamento': typeof LpCabeamentoRoute
  '/lp/headset-callcenter': typeof LpHeadsetCallcenterRoute
  '/lp/headset-logitech': typeof LpHeadsetLogitechRoute
  '/lp/headset-yealink': typeof LpHeadsetYealinkRoute
  '/lp/headsets-poly': typeof LpHeadsetsPolyRoute
  '/lp/poly-studio': typeof LpPolyStudioRoute
  '/lp/rally-bar': typeof LpRallyBarRoute
  '/lp/service-desk': typeof LpServiceDeskRoute
  '/lp/videoconferencia': typeof LpVideoconferenciaRoute
  '/lp/yealink-videoconferencia': typeof LpYealinkVideoconferenciaRoute
  '/': typeof SiteIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/servicos/digital-workspace': typeof SiteServicosDigitalWorkspaceRoute
  '/blog': typeof SiteBlogIndexRoute
  '/servicos': typeof SiteServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/assinaturas': typeof AssinaturasRoute
  '/obrigado': typeof ObrigadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/contato': typeof SiteContatoRoute
  '/_site/produtos': typeof SiteProdutosRoute
  '/_site/sobre': typeof SiteSobreRoute
  '/lp/alocacao-ti': typeof LpAlocacaoTiRoute
  '/lp/cabeamento': typeof LpCabeamentoRoute
  '/lp/headset-callcenter': typeof LpHeadsetCallcenterRoute
  '/lp/headset-logitech': typeof LpHeadsetLogitechRoute
  '/lp/headset-yealink': typeof LpHeadsetYealinkRoute
  '/lp/headsets-poly': typeof LpHeadsetsPolyRoute
  '/lp/poly-studio': typeof LpPolyStudioRoute
  '/lp/rally-bar': typeof LpRallyBarRoute
  '/lp/service-desk': typeof LpServiceDeskRoute
  '/lp/videoconferencia': typeof LpVideoconferenciaRoute
  '/lp/yealink-videoconferencia': typeof LpYealinkVideoconferenciaRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/servicos/digital-workspace': typeof SiteServicosDigitalWorkspaceRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/servicos/': typeof SiteServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinaturas'
    | '/obrigado'
    | '/sitemap.xml'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/lp/alocacao-ti'
    | '/lp/cabeamento'
    | '/lp/headset-callcenter'
    | '/lp/headset-logitech'
    | '/lp/headset-yealink'
    | '/lp/headsets-poly'
    | '/lp/poly-studio'
    | '/lp/rally-bar'
    | '/lp/service-desk'
    | '/lp/videoconferencia'
    | '/lp/yealink-videoconferencia'
    | '/blog/$slug'
    | '/servicos/digital-workspace'
    | '/blog/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assinaturas'
    | '/obrigado'
    | '/sitemap.xml'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/lp/alocacao-ti'
    | '/lp/cabeamento'
    | '/lp/headset-callcenter'
    | '/lp/headset-logitech'
    | '/lp/headset-yealink'
    | '/lp/headsets-poly'
    | '/lp/poly-studio'
    | '/lp/rally-bar'
    | '/lp/service-desk'
    | '/lp/videoconferencia'
    | '/lp/yealink-videoconferencia'
    | '/'
    | '/blog/$slug'
    | '/servicos/digital-workspace'
    | '/blog'
    | '/servicos'
  id:
    | '__root__'
    | '/_site'
    | '/assinaturas'
    | '/obrigado'
    | '/sitemap.xml'
    | '/_site/contato'
    | '/_site/produtos'
    | '/_site/sobre'
    | '/lp/alocacao-ti'
    | '/lp/cabeamento'
    | '/lp/headset-callcenter'
    | '/lp/headset-logitech'
    | '/lp/headset-yealink'
    | '/lp/headsets-poly'
    | '/lp/poly-studio'
    | '/lp/rally-bar'
    | '/lp/service-desk'
    | '/lp/videoconferencia'
    | '/lp/yealink-videoconferencia'
    | '/_site/'
    | '/_site/blog/$slug'
    | '/_site/servicos/digital-workspace'
    | '/_site/blog/'
    | '/_site/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AssinaturasRoute: typeof AssinaturasRoute
  ObrigadoRoute: typeof ObrigadoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LpAlocacaoTiRoute: typeof LpAlocacaoTiRoute
  LpCabeamentoRoute: typeof LpCabeamentoRoute
  LpHeadsetCallcenterRoute: typeof LpHeadsetCallcenterRoute
  LpHeadsetLogitechRoute: typeof LpHeadsetLogitechRoute
  LpHeadsetYealinkRoute: typeof LpHeadsetYealinkRoute
  LpHeadsetsPolyRoute: typeof LpHeadsetsPolyRoute
  LpPolyStudioRoute: typeof LpPolyStudioRoute
  LpRallyBarRoute: typeof LpRallyBarRoute
  LpServiceDeskRoute: typeof LpServiceDeskRoute
  LpVideoconferenciaRoute: typeof LpVideoconferenciaRoute
  LpYealinkVideoconferenciaRoute: typeof LpYealinkVideoconferenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinaturas': {
      id: '/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/lp/yealink-videoconferencia': {
      id: '/lp/yealink-videoconferencia'
      path: '/lp/yealink-videoconferencia'
      fullPath: '/lp/yealink-videoconferencia'
      preLoaderRoute: typeof LpYealinkVideoconferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/videoconferencia': {
      id: '/lp/videoconferencia'
      path: '/lp/videoconferencia'
      fullPath: '/lp/videoconferencia'
      preLoaderRoute: typeof LpVideoconferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/service-desk': {
      id: '/lp/service-desk'
      path: '/lp/service-desk'
      fullPath: '/lp/service-desk'
      preLoaderRoute: typeof LpServiceDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/rally-bar': {
      id: '/lp/rally-bar'
      path: '/lp/rally-bar'
      fullPath: '/lp/rally-bar'
      preLoaderRoute: typeof LpRallyBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/poly-studio': {
      id: '/lp/poly-studio'
      path: '/lp/poly-studio'
      fullPath: '/lp/poly-studio'
      preLoaderRoute: typeof LpPolyStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/headsets-poly': {
      id: '/lp/headsets-poly'
      path: '/lp/headsets-poly'
      fullPath: '/lp/headsets-poly'
      preLoaderRoute: typeof LpHeadsetsPolyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/headset-yealink': {
      id: '/lp/headset-yealink'
      path: '/lp/headset-yealink'
      fullPath: '/lp/headset-yealink'
      preLoaderRoute: typeof LpHeadsetYealinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/headset-logitech': {
      id: '/lp/headset-logitech'
      path: '/lp/headset-logitech'
      fullPath: '/lp/headset-logitech'
      preLoaderRoute: typeof LpHeadsetLogitechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/headset-callcenter': {
      id: '/lp/headset-callcenter'
      path: '/lp/headset-callcenter'
      fullPath: '/lp/headset-callcenter'
      preLoaderRoute: typeof LpHeadsetCallcenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/cabeamento': {
      id: '/lp/cabeamento'
      path: '/lp/cabeamento'
      fullPath: '/lp/cabeamento'
      preLoaderRoute: typeof LpCabeamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/alocacao-ti': {
      id: '/lp/alocacao-ti'
      path: '/lp/alocacao-ti'
      fullPath: '/lp/alocacao-ti'
      preLoaderRoute: typeof LpAlocacaoTiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/sobre': {
      id: '/_site/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SiteSobreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/produtos': {
      id: '/_site/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof SiteProdutosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/servicos/': {
      id: '/_site/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof SiteServicosIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/servicos/digital-workspace': {
      id: '/_site/servicos/digital-workspace'
      path: '/servicos/digital-workspace'
      fullPath: '/servicos/digital-workspace'
      preLoaderRoute: typeof SiteServicosDigitalWorkspaceRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContatoRoute: typeof SiteContatoRoute
  SiteProdutosRoute: typeof SiteProdutosRoute
  SiteSobreRoute: typeof SiteSobreRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteServicosDigitalWorkspaceRoute: typeof SiteServicosDigitalWorkspaceRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteServicosIndexRoute: typeof SiteServicosIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContatoRoute: SiteContatoRoute,
  SiteProdutosRoute: SiteProdutosRoute,
  SiteSobreRoute: SiteSobreRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteServicosDigitalWorkspaceRoute: SiteServicosDigitalWorkspaceRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteServicosIndexRoute: SiteServicosIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AssinaturasRoute: AssinaturasRoute,
  ObrigadoRoute: ObrigadoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LpAlocacaoTiRoute: LpAlocacaoTiRoute,
  LpCabeamentoRoute: LpCabeamentoRoute,
  LpHeadsetCallcenterRoute: LpHeadsetCallcenterRoute,
  LpHeadsetLogitechRoute: LpHeadsetLogitechRoute,
  LpHeadsetYealinkRoute: LpHeadsetYealinkRoute,
  LpHeadsetsPolyRoute: LpHeadsetsPolyRoute,
  LpPolyStudioRoute: LpPolyStudioRoute,
  LpRallyBarRoute: LpRallyBarRoute,
  LpServiceDeskRoute: LpServiceDeskRoute,
  LpVideoconferenciaRoute: LpVideoconferenciaRoute,
  LpYealinkVideoconferenciaRoute: LpYealinkVideoconferenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
