/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YealinkVideoconferenciaRouteImport } from './routes/yealink-videoconferencia'
import { Route as RallyBarRouteImport } from './routes/rally-bar'
import { Route as PolyStudioRouteImport } from './routes/poly-studio'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as HeadsetsPolyRouteImport } from './routes/headsets-poly'
import { Route as HeadsetYealinkRouteImport } from './routes/headset-yealink'
import { Route as HeadsetLogitechRouteImport } from './routes/headset-logitech'
import { Route as HeadsetCallcenterRouteImport } from './routes/headset-callcenter'
import { Route as CabeamentoRouteImport } from './routes/cabeamento'
import { Route as AlocacaoTiRouteImport } from './routes/alocacao-ti'
import { Route as IndexRouteImport } from './routes/index'

const YealinkVideoconferenciaRoute = YealinkVideoconferenciaRouteImport.update({
  id: '/yealink-videoconferencia',
  path: '/yealink-videoconferencia',
  getParentRoute: () => rootRouteImport,
} as any)
const RallyBarRoute = RallyBarRouteImport.update({
  id: '/rally-bar',
  path: '/rally-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const PolyStudioRoute = PolyStudioRouteImport.update({
  id: '/poly-studio',
  path: '/poly-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadsetsPolyRoute = HeadsetsPolyRouteImport.update({
  id: '/headsets-poly',
  path: '/headsets-poly',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadsetYealinkRoute = HeadsetYealinkRouteImport.update({
  id: '/headset-yealink',
  path: '/headset-yealink',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadsetLogitechRoute = HeadsetLogitechRouteImport.update({
  id: '/headset-logitech',
  path: '/headset-logitech',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadsetCallcenterRoute = HeadsetCallcenterRouteImport.update({
  id: '/headset-callcenter',
  path: '/headset-callcenter',
  getParentRoute: () => rootRouteImport,
} as any)
const CabeamentoRoute = CabeamentoRouteImport.update({
  id: '/cabeamento',
  path: '/cabeamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AlocacaoTiRoute = AlocacaoTiRouteImport.update({
  id: '/alocacao-ti',
  path: '/alocacao-ti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alocacao-ti': typeof AlocacaoTiRoute
  '/cabeamento': typeof CabeamentoRoute
  '/headset-callcenter': typeof HeadsetCallcenterRoute
  '/headset-logitech': typeof HeadsetLogitechRoute
  '/headset-yealink': typeof HeadsetYealinkRoute
  '/headsets-poly': typeof HeadsetsPolyRoute
  '/obrigado': typeof ObrigadoRoute
  '/poly-studio': typeof PolyStudioRoute
  '/rally-bar': typeof RallyBarRoute
  '/yealink-videoconferencia': typeof YealinkVideoconferenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alocacao-ti': typeof AlocacaoTiRoute
  '/cabeamento': typeof CabeamentoRoute
  '/headset-callcenter': typeof HeadsetCallcenterRoute
  '/headset-logitech': typeof HeadsetLogitechRoute
  '/headset-yealink': typeof HeadsetYealinkRoute
  '/headsets-poly': typeof HeadsetsPolyRoute
  '/obrigado': typeof ObrigadoRoute
  '/poly-studio': typeof PolyStudioRoute
  '/rally-bar': typeof RallyBarRoute
  '/yealink-videoconferencia': typeof YealinkVideoconferenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alocacao-ti': typeof AlocacaoTiRoute
  '/cabeamento': typeof CabeamentoRoute
  '/headset-callcenter': typeof HeadsetCallcenterRoute
  '/headset-logitech': typeof HeadsetLogitechRoute
  '/headset-yealink': typeof HeadsetYealinkRoute
  '/headsets-poly': typeof HeadsetsPolyRoute
  '/obrigado': typeof ObrigadoRoute
  '/poly-studio': typeof PolyStudioRoute
  '/rally-bar': typeof RallyBarRoute
  '/yealink-videoconferencia': typeof YealinkVideoconferenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alocacao-ti'
    | '/cabeamento'
    | '/headset-callcenter'
    | '/headset-logitech'
    | '/headset-yealink'
    | '/headsets-poly'
    | '/obrigado'
    | '/poly-studio'
    | '/rally-bar'
    | '/yealink-videoconferencia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alocacao-ti'
    | '/cabeamento'
    | '/headset-callcenter'
    | '/headset-logitech'
    | '/headset-yealink'
    | '/headsets-poly'
    | '/obrigado'
    | '/poly-studio'
    | '/rally-bar'
    | '/yealink-videoconferencia'
  id:
    | '__root__'
    | '/'
    | '/alocacao-ti'
    | '/cabeamento'
    | '/headset-callcenter'
    | '/headset-logitech'
    | '/headset-yealink'
    | '/headsets-poly'
    | '/obrigado'
    | '/poly-studio'
    | '/rally-bar'
    | '/yealink-videoconferencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlocacaoTiRoute: typeof AlocacaoTiRoute
  CabeamentoRoute: typeof CabeamentoRoute
  HeadsetCallcenterRoute: typeof HeadsetCallcenterRoute
  HeadsetLogitechRoute: typeof HeadsetLogitechRoute
  HeadsetYealinkRoute: typeof HeadsetYealinkRoute
  HeadsetsPolyRoute: typeof HeadsetsPolyRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PolyStudioRoute: typeof PolyStudioRoute
  RallyBarRoute: typeof RallyBarRoute
  YealinkVideoconferenciaRoute: typeof YealinkVideoconferenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yealink-videoconferencia': {
      id: '/yealink-videoconferencia'
      path: '/yealink-videoconferencia'
      fullPath: '/yealink-videoconferencia'
      preLoaderRoute: typeof YealinkVideoconferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rally-bar': {
      id: '/rally-bar'
      path: '/rally-bar'
      fullPath: '/rally-bar'
      preLoaderRoute: typeof RallyBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poly-studio': {
      id: '/poly-studio'
      path: '/poly-studio'
      fullPath: '/poly-studio'
      preLoaderRoute: typeof PolyStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headsets-poly': {
      id: '/headsets-poly'
      path: '/headsets-poly'
      fullPath: '/headsets-poly'
      preLoaderRoute: typeof HeadsetsPolyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headset-yealink': {
      id: '/headset-yealink'
      path: '/headset-yealink'
      fullPath: '/headset-yealink'
      preLoaderRoute: typeof HeadsetYealinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headset-logitech': {
      id: '/headset-logitech'
      path: '/headset-logitech'
      fullPath: '/headset-logitech'
      preLoaderRoute: typeof HeadsetLogitechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headset-callcenter': {
      id: '/headset-callcenter'
      path: '/headset-callcenter'
      fullPath: '/headset-callcenter'
      preLoaderRoute: typeof HeadsetCallcenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabeamento': {
      id: '/cabeamento'
      path: '/cabeamento'
      fullPath: '/cabeamento'
      preLoaderRoute: typeof CabeamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alocacao-ti': {
      id: '/alocacao-ti'
      path: '/alocacao-ti'
      fullPath: '/alocacao-ti'
      preLoaderRoute: typeof AlocacaoTiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlocacaoTiRoute: AlocacaoTiRoute,
  CabeamentoRoute: CabeamentoRoute,
  HeadsetCallcenterRoute: HeadsetCallcenterRoute,
  HeadsetLogitechRoute: HeadsetLogitechRoute,
  HeadsetYealinkRoute: HeadsetYealinkRoute,
  HeadsetsPolyRoute: HeadsetsPolyRoute,
  ObrigadoRoute: ObrigadoRoute,
  PolyStudioRoute: PolyStudioRoute,
  RallyBarRoute: RallyBarRoute,
  YealinkVideoconferenciaRoute: YealinkVideoconferenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
